export const courses = [
    {
        id: 1,
        title: "React Fundamentals",
        instructor: "John Doe",
        instructorImg: "https://randomuser.me/api/portraits/men/32.jpg",
        image: "https://images.unsplash.com/photo-1653387300291-bfa1eeb90e16?q=80&w=1740&auto=format&fit=crop",
        duration: "6 weeks",
        startDate: "2025-07-01",
        price: "49.99",
        rating: 4.8,
        students: 320,
        description: "Learn the fundamentals of React.js and build dynamic, component-based web applications."
    },
    {
        id: 2,
        title: "Node.js Backend Mastery",
        instructor: "Jane Smith",
        instructorImg: "https://randomuser.me/api/portraits/women/44.jpg",
        image: "https://images.unsplash.com/photo-1650234083227-74c0700b295a?q=80&w=1740&auto=format&fit=crop",
        duration: "8 weeks",
        startDate: "2025-07-10",
        price: "59.99",
        rating: 4.6,
        students: 210,
        description: "Master backend development using Node.js with real-world APIs and databases."
    },
    {
        id: 3,
        title: "UI/UX Design Essentials",
        instructor: "Emily White",
        instructorImg: "https://randomuser.me/api/portraits/women/68.jpg",
        image: "https://images.unsplash.com/photo-1559028012-481c04fa702d?q=80&w=1472&auto=format&fit=crop",
        duration: "4 weeks",
        startDate: "2025-07-15",
        price: "39.99",
        rating: 4.9,
        students: 400,
        description: "Discover the principles of modern UI/UX design and improve your digital product designs."
    },
    {
        id: 4,
        title: "Python Data Science",
        instructor: "Michael Chen",
        instructorImg: "https://randomuser.me/api/portraits/men/55.jpg",
        image: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?q=80&w=1740&auto=format&fit=crop",
        duration: "10 weeks",
        startDate: "2025-07-20",
        price: "69.99",
        rating: 4.7,
        students: 285,
        description: "Master data analysis and machine learning with Python, pandas, and scikit-learn."
    },
    {
        id: 5,
        title: "Full-Stack JavaScript",
        instructor: "Sarah Johnson",
        instructorImg: "https://randomuser.me/api/portraits/women/23.jpg",
        image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=1740&auto=format&fit=crop",
        duration: "12 weeks",
        startDate: "2025-08-01",
        price: "89.99",
        rating: 4.5,
        students: 150,
        description: "Complete full-stack development course covering React, Node.js, MongoDB, and deployment."
    },
    {
        id: 6,
        title: "Mobile App Development",
        instructor: "David Rodriguez",
        instructorImg: "https://randomuser.me/api/portraits/men/78.jpg",
        image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=1740&auto=format&fit=crop",
        duration: "9 weeks",
        startDate: "2025-08-05",
        price: "79.99",
        rating: 4.6,
        students: 195,
        description: "Build cross-platform mobile apps using React Native and deploy to app stores."
    },
    {
        id: 7,
        title: "Digital Marketing Bootcamp",
        instructor: "Lisa Anderson",
        instructorImg: "https://randomuser.me/api/portraits/women/34.jpg",
        image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1740&auto=format&fit=crop",
        duration: "6 weeks",
        startDate: "2025-08-12",
        price: "44.99",
        rating: 4.8,
        students: 380,
        description: "Master SEO, social media marketing, and Google Ads to grow your online presence."
    },
    {
        id: 8,
        title: "Cloud Computing with AWS",
        instructor: "Robert Kim",
        instructorImg: "https://randomuser.me/api/portraits/men/91.jpg",
        image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1740&auto=format&fit=crop",
        duration: "7 weeks",
        startDate: "2025-08-18",
        price: "64.99",
        rating: 4.4,
        students: 165,
        description: "Learn cloud architecture, deployment, and management using Amazon Web Services."
    }
];