export const courses = [
    {
        id: 1,
        title: "React Fundamentals",
        instructor: "John Doe",
        instructorImg: "https://randomuser.me/api/portraits/men/32.jpg",
        image: "https://images.unsplash.com/photo-1653387300291-bfa1eeb90e16?q=80&w=1740&auto=format&fit=crop",
        duration: "6 weeks",
        startDate: "2025-07-01",
        price: "49.99",
        rating: 4.8,
        students: 320,
        description: "Learn the fundamentals of React.js and build dynamic, component-based web applications."
    },
    {
        id: 2,
        title: "Node.js Backend Mastery",
        instructor: "Jane Smith",
        instructorImg: "https://randomuser.me/api/portraits/women/44.jpg",
        image: "https://images.unsplash.com/photo-1650234083227-74c0700b295a?q=80&w=1740&auto=format&fit=crop",
        duration: "8 weeks",
        startDate: "2025-07-10",
        price: "59.99",
        rating: 4.6,
        students: 210,
        description: "Master backend development using Node.js with real-world APIs and databases."
    },
    {
        id: 3,
        title: "UI/UX Design Essentials",
        instructor: "Emily White",
        instructorImg: "https://randomuser.me/api/portraits/women/68.jpg",
        image: "https://images.unsplash.com/photo-1559028012-481c04fa702d?q=80&w=1472&auto=format&fit=crop",
        duration: "4 weeks",
        startDate: "2025-07-15",
        price: "39.99",
        rating: 4.9,
        students: 400,
        description: "Discover the principles of modern UI/UX design and improve your digital product designs."
    },
    {
        id: 4,
        title: "Python Data Science",
        instructor: "Michael Chen",
        instructorImg: "https://randomuser.me/api/portraits/men/55.jpg",
        image: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?q=80&w=1740&auto=format&fit=crop",
        duration: "10 weeks",
        startDate: "2025-07-20",
        price: "69.99",
        rating: 4.7,
        students: 285,
        description: "Master data analysis and machine learning with Python, pandas, and scikit-learn."
    },
    {
        id: 5,
        title: "Full-Stack JavaScript",
        instructor: "Sarah Johnson",
        instructorImg: "https://randomuser.me/api/portraits/women/23.jpg",
        image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=1740&auto=format&fit=crop",
        duration: "12 weeks",
        startDate: "2025-08-01",
        price: "89.99",
        rating: 4.5,
        students: 150,
        description: "Complete full-stack development course covering React, Node.js, MongoDB, and deployment."
    },
    {
        id: 6,
        title: "Mobile App Development",
        instructor: "David Rodriguez",
        instructorImg: "https://randomuser.me/api/portraits/men/78.jpg",
        image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=1740&auto=format&fit=crop",
        duration: "9 weeks",
        startDate: "2025-08-05",
        price: "79.99",
        rating: 4.6,
        students: 195,
        description: "Build cross-platform mobile apps using React Native and deploy to app stores."
    },
    {
        id: 7,
        title: "Digital Marketing Bootcamp",
        instructor: "Lisa Anderson",
        instructorImg: "https://randomuser.me/api/portraits/women/34.jpg",
        image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1740&auto=format&fit=crop",
        duration: "6 weeks",
        startDate: "2025-08-12",
        price: "44.99",
        rating: 4.8,
        students: 380,
        description: "Master SEO, social media marketing, and Google Ads to grow your online presence."
    },
    {
        id: 8,
        title: "Cloud Computing with AWS",
        instructor: "Robert Kim",
        instructorImg: "https://randomuser.me/api/portraits/men/91.jpg",
        image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1740&auto=format&fit=crop",
        duration: "7 weeks",
        startDate: "2025-08-18",
        price: "64.99",
        rating: 4.4,
        students: 165,
        description: "Learn cloud architecture, deployment, and management using Amazon Web Services."
    }
];

export const assignments = [
    {
        id: 1,
        title: "React Component Architecture Project",
        course: "React Advanced",
        courseId: "react-adv-001",
        instructor: "Sarah Johnson",
        instructorImg: "https://randomuser.me/api/portraits/women/1.jpg",
        type: "Project",
        status: "pending",
        difficulty: "Advanced",
        estimatedTime: "8-10 hours",
        dueDate: "2024-06-20",
        submittedDate: null,
        grade: null,
        maxPoints: 100,
        description: "Build a scalable component architecture using React hooks and context API. Focus on reusability, performance optimization, and proper state management patterns.",
        priority: "high",
        tags: ["React", "Hooks", "Architecture", "State Management"],
        attachments: [
            { name: "project-requirements.pdf", size: "2.1 MB", type: "pdf" },
            { name: "starter-template.zip", size: "856 KB", type: "zip" }
        ],
        submissionFormat: ["Code Repository", "Documentation", "Demo Video"],
        category: "Frontend Development"
    },
    {
        id: 2,
        title: "Database Design Quiz",
        course: "Node.js Fundamentals",
        courseId: "node-fund-002",
        instructor: "Michael Chen",
        instructorImg: "https://randomuser.me/api/portraits/men/2.jpg",
        type: "Quiz",
        status: "completed",
        difficulty: "Intermediate",
        estimatedTime: "45 minutes",
        dueDate: "2024-06-15",
        submittedDate: "2024-06-14",
        grade: 85,
        maxPoints: 100,
        description: "Test your knowledge of database design principles, normalization, and SQL optimization techniques.",
        priority: "medium",
        tags: ["Database", "SQL", "Normalization", "Design Patterns"],
        attachments: [
            { name: "study-guide.pdf", size: "1.8 MB", type: "pdf" }
        ],
        submissionFormat: ["Online Quiz"],
        category: "Backend Development",
        feedback: "Great understanding of normalization concepts. Review indexing strategies for better performance."
    },
    {
        id: 3,
        title: "Security Vulnerability Assessment",
        course: "Web Security",
        courseId: "websec-003",
        instructor: "Emily Rodriguez",
        instructorImg: "https://randomuser.me/api/portraits/women/3.jpg",
        type: "Assignment",
        status: "overdue",
        difficulty: "Advanced",
        estimatedTime: "6-8 hours",
        dueDate: "2024-06-10",
        submittedDate: null,
        grade: null,
        maxPoints: 75,
        description: "Conduct a comprehensive security assessment of a web application. Identify vulnerabilities, document findings, and propose remediation strategies.",
        priority: "high",
        tags: ["Security", "Penetration Testing", "OWASP", "Vulnerability Assessment"],
        attachments: [
            { name: "target-application.zip", size: "5.2 MB", type: "zip" },
            { name: "assessment-template.docx", size: "124 KB", type: "docx" }
        ],
        submissionFormat: ["Security Report", "Executive Summary"],
        category: "Cybersecurity"
    },
    {
        id: 4,
        title: "API Documentation Review",
        course: "Node.js Fundamentals",
        courseId: "node-fund-002",
        instructor: "Michael Chen",
        instructorImg: "https://randomuser.me/api/portraits/men/2.jpg",
        type: "Assignment",
        status: "submitted",
        difficulty: "Beginner",
        estimatedTime: "3-4 hours",
        dueDate: "2024-06-25",
        submittedDate: "2024-06-18",
        grade: null,
        maxPoints: 50,
        description: "Review and improve existing API documentation. Add examples, clarify endpoints, and ensure comprehensive coverage of all features.",
        priority: "low",
        tags: ["API", "Documentation", "REST", "Technical Writing"],
        attachments: [
            { name: "current-docs.pdf", size: "892 KB", type: "pdf" },
            { name: "api-examples.json", size: "45 KB", type: "json" }
        ],
        submissionFormat: ["Updated Documentation", "Change Log"],
        category: "Backend Development"
    },
    {
        id: 5,
        title: "React Hooks Deep Dive",
        course: "React Advanced",
        courseId: "react-adv-001",
        instructor: "Sarah Johnson",
        instructorImg: "https://randomuser.me/api/portraits/women/1.jpg",
        type: "Essay",
        status: "pending",
        difficulty: "Intermediate",
        estimatedTime: "4-5 hours",
        dueDate: "2024-06-30",
        submittedDate: null,
        grade: null,
        maxPoints: 80,
        description: "Write a comprehensive essay exploring advanced React hooks patterns, custom hooks development, and performance optimization techniques.",
        priority: "medium",
        tags: ["React", "Hooks", "Performance", "Custom Hooks"],
        attachments: [
            { name: "essay-guidelines.pdf", size: "678 KB", type: "pdf" },
            { name: "reference-materials.zip", size: "2.8 MB", type: "zip" }
        ],
        submissionFormat: ["Academic Essay", "Code Examples"],
        category: "Frontend Development"
    },
    {
        id: 6,
        title: "Machine Learning Model Implementation",
        course: "AI & Machine Learning",
        courseId: "ai-ml-004",
        instructor: "Dr. James Wilson",
        instructorImg: "https://randomuser.me/api/portraits/men/4.jpg",
        type: "Project",
        status: "pending",
        difficulty: "Advanced",
        estimatedTime: "12-15 hours",
        dueDate: "2024-07-05",
        submittedDate: null,
        grade: null,
        maxPoints: 120,
        description: "Implement and train a machine learning model for image classification. Compare different algorithms and optimize for accuracy and performance.",
        priority: "high",
        tags: ["Machine Learning", "Python", "TensorFlow", "Image Classification"],
        attachments: [
            { name: "dataset.zip", size: "45.2 MB", type: "zip" },
            { name: "project-specification.pdf", size: "1.9 MB", type: "pdf" }
        ],
        submissionFormat: ["Jupyter Notebook", "Model Files", "Performance Report"],
        category: "Artificial Intelligence"
    }
];


export const quizzes = [
    {
        id: 1,
        title: "React Basics Quiz",
        course: "React Fundamentals",
        status: "completed",
        questions: 10,
        score: 9,
        maxScore: 10,
        startDate: "2024-06-10",
        endDate: "2024-06-15"
    },
    {
        id: 2,
        title: "Node.js Routing Quiz",
        course: "Node.js Backend Mastery",
        status: "pending",
        questions: 12,
        score: null,
        maxScore: 12,
        startDate: "2024-06-20",
        endDate: "2024-06-25"
    },
    {
        id: 3,
        title: "UI/UX Design Principles",
        course: "UI/UX Design Essentials",
        status: "available",
        questions: 15,
        score: null,
        maxScore: 15,
        startDate: "2024-06-18",
        endDate: "2024-06-22"
    }
];
